### ISSUE TITLE
generateWikiConfig won't work for some languages 

### ISSUE THREAD

**Issue by claeyzre** [dkpro/dkpro-jwpl#159] opened 2018-06-08 09:12 UTC
Hi,

I am trying to parse wiki-text from many wikipedias. For some languages the configs output from generateWikiConfig work fine. But I end up with that kind of stacktraces when I try for example for Japanese. I am using "org.sweble.wikitext" % "swc-engine" % "3.1.7". Checking the issues, related bugs should have been fixed in the 3.1.7.  

```
java.lang.IllegalArgumentException: The name `sub' was already registered by the alias `sub' when trying to register it for alias `img_sub'.
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63)
	at PageBuilder$.apply(PageBuilder.scala:59)
	at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27)
	at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139)
	at Xml2FasttextDS.main(Xml2FasttextDS.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: The name `名前空間:' was already registered by the alias `namespace' when trying to register it for alias `ns'.
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63)
	at PageBuilder$.apply(PageBuilder.scala:59)
	at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27)
	at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139)
	at Xml2FasttextDS.main(Xml2FasttextDS.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: The name `noerror' was already registered by the alias `defaultsort_noerror' when trying to register it for alias `displaytitle_noerror'.
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63)
	at PageBuilder$.apply(PageBuilder.scala:59)
	at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27)
	at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139)
	at Xml2FasttextDS.main(Xml2FasttextDS.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: The name `noreplace' was already registered by the alias `defaultsort_noreplace' when trying to register it for alias `displaytitle_noreplace'.
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63)
	at PageBuilder$.apply(PageBuilder.scala:59)
	at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27)
	at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139)
	at Xml2FasttextDS.main(Xml2FasttextDS.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: No alias registered for parser function `ns'.
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addParserFunction(WikiConfigImpl.java:449)
	at org.sweble.wikitext.engine.config.WikiConfigImpl.addParserFunctionGroup(WikiConfigImpl.java:430)
	at org.sweble.wikitext.engine.utils.DefaultConfig.addParserFunctions(DefaultConfig.java:573)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:114)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78)
	at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63)
	at PageBuilder$.apply(PageBuilder.scala:59)
	at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27)
	at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139)
	at Xml2FasttextDS.main(Xml2FasttextDS.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
[success] Total time: 1 s, completed Jun 8, 2018 11:00:56 AM```

Can you tell me if that's possible to generate Japanese WikiConfig with this method or should I do it manually ?

Thanks for your help,

**Comment by mawiesne** [comment] 2018-06-22 06:39
I can confirm the output of the stacktrace for other languages than Japanese: German/French... are also affected. It seems that **Swebble** in version 3.1.7 (or below) has issues at `WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386)`.  The code that prints out these errors to the standard console even has a documented TODO stating 

> // TODO resolve conflicts problem

see: `LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204)` and below. 

Besides the actual problem with multiple registrations ("was already registered by the alias") , it would be better to use a logging framework here, as otherwise it will not be captured within log files, given a server environment (e.g., application containers...).

Can @ferschke or @reckart have a look at this? Or: contact _Samy Ateia_, samyateia [at] hotmail.de

**Comment by reckart** [comment] 2018-06-22 08:21
@mawiesne I'm trying to help out with PRs and build infrastructure etc a bit and I could even try running a release, but unfortunately, I have no spare resources to actually work on the code.

**Comment by tgalery** [comment] 2018-06-22 08:50
fyi I took a look at the code and this is not an error per se. The language configurator tries to associate some aliases for some specific tags and prints the stacktrace if the tag is already in use. The problem is in Sweble https://github.com/sweble/sweble-wikitext/issues/72 and not something that lies in the code of dkpro. That being said, you should be able to create a japanese config even with these stacktraces being printed.

**Comment by claeyzre** [comment] 2018-06-22 08:54
On some languages, the stacktraces are just printed and the config seems correct and the parsing goes on. On some other languages like Japanese, this leads to not just a print but in a real exception and no config are created.

**Comment by mawiesne** [comment] 2018-06-22 09:10
@reckart Thanks for your support. Just want to raise awareness that both #159 and #160 should be tackled before a release of 1.2.0 makes sense. IMHO #160 is a blocker atm. For #159 I'd say it could be compensated (by ignoring it) even though @claeyzre might have a point that things can fail later during runtime. @claeyzre Can you pls add a full stacktrace of the exceptions you encounter "later on" for a Japanese language/environment.

**Comment by claeyzre** [comment] 2018-06-22 09:13
@mawiesne  The stacktrace is the one I gave you. The thing is that sometimes it's just printed and my program carries on. Sometimes it stops directly after the print.

**Comment by mawiesne** [comment] 2018-07-17 13:43
@tgalery Could you look into this issue?

**Comment by tgalery** [comment] 2018-07-19 09:37
Like I said here https://github.com/dkpro/dkpro-jwpl/issues/159#issuecomment-399371085 AFAIK the language config does work, it just prints misleading stacktraces that shouldn't be printed. The fix for this would be in sweble not here. Once that's fixed there, we can update the dependency here.

**Comment by tgalery** [comment] 2018-07-19 09:40
Will try to reproduce the bug first. But probably this would be a fix in sweble.

**Comment by mawiesne** [comment] 2018-07-19 09:50
Sounds reasonable. If you could provide a test case that demonstrates this scenario that would be of great help.

**Comment by mawiesne** [comment] 2018-07-19 09:52
@reckart Why can't I assign @tgalery for this issue? Is he missing some rights?

**Comment by reckart** [comment] 2018-07-19 12:14
@tgalery I have added you to the JWPL dev team so @mawiesne can assign issues to you. This also allows you to create PRs directly in the JWPL repo. However, the settings (should) prevent pushes directly to the master branch - PRs are required and need to be approved as usual.

**Comment by reckart** [comment] 2018-07-19 12:14
@tgalery oh, and you can approve PRs by others now.

**Comment by tgalery** [comment] 2018-07-25 15:11
FYI, I've confirmed the bug. For some language, i.e. German, we can create the config, whereas for some others, like Japanese, we cannot. I still have the feeling that the best place to fix it would be in sweble, so I will create an issue there and reference it here. If things get nasty too quickly, I might just handle the exception and return the English config for the languages that are throwing the error.

**Comment by tgalery** [comment] 2018-07-25 15:17
and here's some note to self:
```
scala> lastException.getClass.getCanonicalName
res5: String = java.lang.IllegalArgumentException

scala> lastException.getCause
res6: Throwable = null
```

**Comment by mawiesne** [comment] 2018-08-02 18:37
@tgalery Could you cross-link the issue in Sweble in here?

**Comment by tgalery** [comment] 2018-08-03 12:34
Sure, the issue is this https://github.com/sweble/sweble-wikitext/issues/72 I've been swamped this week, but should crack on it next week.

**Comment by tgalery** [comment] 2018-09-28 12:10
Can someone test PR #202 to confirm this issue is gone ?

**Closed** 2018-10-10 13:20 UTC
Labels: :sos: help wanted, major, 🐛Bug
